# Generated by Django 3.2.8 on 2021-10-23 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_auto_20211023_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('', 'Unknown Yet'), ('ft', 'Full time'), ('pt', 'Part time')], max_length=2),
        ),
    ]
