# Generated by Django 3.2.8 on 2021-10-23 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_alter_job_job_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('', 'Unknown Yet'), ('ft', 'Full time'), ('pt', 'Part time')], default='ft', max_length=2),
        ),
    ]
