# Generated by Django 3.2.8 on 2021-10-23 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_alter_job_job_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(default='', max_length=1000, null=True),
        ),
    ]
