# Generated by Django 3.2.8 on 2021-10-23 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_auto_20211023_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
    ]
